### ISSUE TITLE
stable / development workflow is tedious

### ISSUE THREAD

**Issue by asottile** [Yelp/venv-update#148]
- This project is not nearly big enough to warrant such a complicated release workflow
- We don't ever expect to merge a broken branch into "development"

Can we go back to a simpler workflow where `master` is the default branch and things are easier?

**Comment by chriskuehl** [comment]
+1, I too prefer just using master. The stated benefit at the time of having a "stable" branch was that the way people download venv-update is by going to GitHub and grabbing it out of the repo and we don't want them getting in-progress versions.

But the default branch is still "develop" since we didn't want people accidentally making PRs against the wrong base branch (you can't change it without closing/reopening another, thanks GitHub) so people will make this mistake anyway.

And we have that `curl | bash` stuff now for people who live dangerously  which could be made to get the latest version without using the `stable` branch (mutable tag? kinda sucks, but it works)
