### ISSUE TITLE
Drop python2.6 support

### ISSUE THREAD

**Issue by chriskuehl** [Yelp/venv-update#157]

**Comment by asottile** [comment]
at least at yelp this'll be difficult because venv-update imports virtualenv from the system:

https://github.com/Yelp/venv-update/blob/4b4764a0b19c06a4f25f372c60138f17ac3aa774/venv_update.py#L296

Though I imagine we could always invoke this script with python2.7 and jam virtualenv into the py27 dist-packages somehow... hmmm...

**Comment by asottile** [comment]
Looks like it's time, wheel has dropped py26 support making it difficult to run our test suite

**Comment by asottile** [comment]
via #204
